spring:
  datasource:
    url: jdbc:mysql://182.61.22.104:3306/DsWdi?useUnicode=true&characterEncoding=utf8
    username: root
    password: miaomiaomiao
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false #关闭缓存
mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  #端口号
  port: 8888


#####################################################################
########################  开发环境profile  ##########################
#####################################################################
logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file:
    name: ./chip.log

